language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Home of Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot2-withAws-webservice *
  - mkdir -p deploy
  - mv springboot2-withAws-webservice.zip deploy/springboot2-withAws-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot2-withaws-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# Alarm when CI implement is completed by email
notifications:
  email:
    recipients:
      - sckwon770@gmail.com