language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Home of Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Alarm when CI implement is completed by email
notifications:
  email:
    recipients:
      - sckwon770@gmail.com